### ISSUE TITLE
feature request: add custom SPI pins 

### ISSUE THREAD

**Issue by hgpt** [Marzogh/SPIMemory#113]
![GitHub issue state](https://img.shields.io/github/issues/detail/s/Marzogh/SPIFlash/113.svg) ![GitHub issue title](https://img.shields.io/github/issues/detail/title/Marzogh/SPIFlash/113.svg) ![GitHub issue author](https://img.shields.io/github/issues/detail/u/Marzogh/SPIFlash/113.svg) ![GitHub issue label](https://img.shields.io/github/issues/detail/label/Marzogh/SPIFlash/113.svg) ![GitHub issue comments](https://img.shields.io/github/issues/detail/comments/Marzogh/SPIFlash/113.svg) ![GitHub issue age](https://img.shields.io/github/issues/detail/age/Marzogh/SPIFlash/113.svg) ![GitHub issue last update](https://img.shields.io/github/issues/detail/last-update/Marzogh/SPIFlash/113.svg)
###### ---------------------------- **DO NOT DELETE OR EDIT** anything above this line ----------------------------
Some uC like the ESP32 allow the user to route the SPI pins (MISO,MOSI,SCK) to any GPIO pins trough the GPIO MUX matrix. It could prove really handy to be able to change the SPI pins in the Arduino IDE sketch as desired.

**Comment by Marzogh** [comment]
Resolved as of commit 444fde0
