### ISSUE TITLE
BluePill Support request

### ISSUE THREAD

**Issue by KingJimmy27** [Marzogh/SPIMemory#116]
![GitHub issue state](https://img.shields.io/github/issues/detail/s/Marzogh/SPIFlash/116.svg) ![GitHub issue title](https://img.shields.io/github/issues/detail/title/Marzogh/SPIFlash/116.svg) ![GitHub issue author](https://img.shields.io/github/issues/detail/u/Marzogh/SPIFlash/116.svg) ![GitHub issue label](https://img.shields.io/github/issues/detail/label/Marzogh/SPIFlash/116.svg) ![GitHub issue comments](https://img.shields.io/github/issues/detail/comments/Marzogh/SPIFlash/116.svg) ![GitHub issue age](https://img.shields.io/github/issues/detail/age/Marzogh/SPIFlash/116.svg) ![GitHub issue last update](https://img.shields.io/github/issues/detail/last-update/Marzogh/SPIFlash/116.svg)
###### ---------------------------- **DO NOT DELETE OR EDIT** anything above this line ----------------------------

# Issue details

**I'm submitting a ...**
  - [x] feature request  

Do the checklist before filing an issue:

- [x] Is this an idea for a feature? Post the feature request as an issue here with a title that clearly says "Feature Request".
  
When opening an issue please include the following details:
-------------------------------------------------------------

- [x] Do you want to request a *feature* or report a *bug*? - Feature request
- [x] Which library version are you using? - v3.0.0
- [x] Which Arduino IDE version are you compiling the library on? - v1.8.5
- [x] Which OS are you compiling your code on? [Linux / Mac / Windows] - Windows 10
- [x] Which microcontroller platform are you using? - STM32 (BluePill)
- [x] Which Flash memory module are you using? - W25Q80BV
- [x] What is the current behavior? - FlashDiagnostics does not work
- [x] What is the expected behavior? - Standard FlashDiagnostics behaviour
-----------------------------
###### Feature Requests only

- [x] If this is a feature request, what is the motivation / use case for changing the behavior?
 Add compatibility for the BluePill board. Increases the user base of the library
----------------------------

- [x] Other information (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context etc.)
 I am using http://www.visualmicro.com/ to build my projects and not the Arduino ide, however the Visual Micro does use the Arduino software.
I never use a bootloader only a cheap ISP like STM-LINK V2 

_Make sure to add **all the information needed to understand the bug/feature** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information._

**Comment by Marzogh** [comment]
The code in the development branch as of today's commit (703f609781c7d8e866f79f415ef5e254cb324799) works with the BluePill. The next release - v3.3.0 will come with official support for this platform. 🙂

**Comment by FarazArdu** [comment]
hi, do the library supports stm32 Blue Pill ? thanks
