### ISSUE TITLE
Feature Request: Support for Adafruits nRf52 chip (Arduino core available)

### ISSUE THREAD

**Issue by jubueche** [Marzogh/SPIMemory#127]
![GitHub issue state](https://img.shields.io/github/issues/detail/s/Marzogh/SPIFlash/127.svg) ![GitHub issue title](https://img.shields.io/github/issues/detail/title/Marzogh/SPIFlash/127.svg) ![GitHub issue author](https://img.shields.io/github/issues/detail/u/Marzogh/SPIFlash/127.svg) ![GitHub issue label](https://img.shields.io/github/issues/detail/label/Marzogh/SPIFlash/127.svg) ![GitHub issue comments](https://img.shields.io/github/issues/detail/comments/Marzogh/SPIFlash/127.svg) ![GitHub issue age](https://img.shields.io/github/issues/detail/age/Marzogh/SPIFlash/127.svg) ![GitHub issue last update](https://img.shields.io/github/issues/detail/last-update/Marzogh/SPIFlash/127.svg)
###### ---------------------------- **DO NOT DELETE OR EDIT** anything above this line ----------------------------
# Issue details

**I'm submitting a ...**
  - [x] feature request
  
Do the checklist before filing an issue:
- [x] Is this an idea for a feature? Post the feature request as an issue here with a title that clearly says "Feature Request".

**Comment by jubueche** [comment]
Would it be much effort including the nRf52 from Adafruit?

**Comment by jubueche** [comment]
Great. Are you also supporting the Spansion S25FL256S?

**Comment by Marzogh** [comment]
I don't currently own an S25FL256S, but it should (in theory work with the latest version of the library (>=[v3.3.0](https://github.com/Marzogh/SPIMemory/tree/v3.3.0)). 

Also, [v3.4.0](https://github.com/Marzogh/SPIMemory/tree/v3.4.0) onwards will support the nRF52 platform by default (As of commit 2924cf1 in the [development](https://github.com/Marzogh/SPIMemory/tree/development) branch). My apologies for the delay in getting around to this - I was away, unwell, for most of last year and only just got back into this project in late April this year.
