### ISSUE TITLE
Bug Report/Annoyance: 3.2.0 uses twice the program memory of 3.1.0

### ISSUE THREAD

**Issue by Andon-A** [Marzogh/SPIMemory#135]
![GitHub issue state](https://img.shields.io/github/issues/detail/s/Marzogh/SPIFlash/135.svg) ![GitHub issue title](https://img.shields.io/github/issues/detail/title/Marzogh/SPIFlash/135.svg)
![GitHub issue author](https://img.shields.io/github/issues/detail/u/Marzogh/SPIFlash/135.svg) ![GitHub issue label](https://img.shields.io/github/issues/detail/label/Marzogh/SPIFlash/135.svg) ![GitHub issue comments](https://img.shields.io/github/issues/detail/comments/Marzogh/SPIFlash/135.svg)
![GitHub issue age](https://img.shields.io/github/issues/detail/age/Marzogh/SPIFlash/135.svg) ![GitHub issue last update](https://img.shields.io/github/issues/detail/last-update/Marzogh/SPIFlash/135.svg)
###### ---------------------------- **DO NOT DELETE OR EDIT** anything above this line ----------------------------

Arduino IDE 1.8.5, using alternately SPIFlash 3.1.0 and SPIMemory 3.2.0, under Windows 10.

RUNDIAGNOSTIC and PRINTNAMECHANGEALERT (Lines 36 and 64) in SPIFlash.h are commented out to save space for 3.1.0
RUNDIAGNOSTIC (Line 35) in SPIMemory.h is commented out to save space for 3.2.0

Board settings are Arduino Pro/Pro Mini, ATMega328p, 3.3v/8mHz

The following code compiles to 2784 bytes in 3.1.0:
```
#include <SPIFlash.h>
SPIFlash flash(5);

void setup() {
  flash.begin();
}

void loop() {

}
```

Replacing `SPIFlash.h` with `SPIMemory.h` for using with 3.2.0 compiles with 5636 bytes, over double that of 3.1.0.

This is of particular interest to me as the [program I am using it in](https://github.com/PhoenixbornTech/DigiBadge_Mini) compiles to precisely 30720 bytes with 3.1.0 - The maximum a 328p can utilize. For ease of users compiling their own code, I would like to be able to give simple instructions on what needs to be commented out. For 3.1.0, this is "Comment out lines 36 and 64 in SPIFlash.h" - For 3.2.0 this "Simple" memory saver doesn't work.

I haven't had time to investigate the *cause* of the space usage increase (I'm flying out to Seattle tomorrow morning), but I feel such incredible balooning seems to be a bug.

If this is expected performance, then this can be treated as a feature request for space saving measures.

**Comment by Marzogh** [comment]
Ugh! That's something that I missed with the name change issue.

I will fix this for you ASAP and get a bugfix release out within a week with the option of turning off the new features. That should take the memory footprint back down. Thanks for catching it.

**Comment by Marzogh** [comment]
Commit e24a2bc fixes this issue and reduces the footprint even further. If you make sure that #define RUNDIAGNOSTIC and #USES_SFDP are commented out, your code is currently compiling ti 30342 bytes instead of the previous 30720 bytes. Feel free to use the code from the development branch for now. I have a few more changes to make before the code goes stable and I push out v 3.2.1

**Comment by Andon-A** [comment]
I've been away pretty much since I posted this. Awesome to come back to! Thanks a lot.

**Comment by Marzogh** [comment]
Anytime! v3.2.1 is currently out in the wild and should fix the problem you had. 🙂👍🏽
