### ISSUE TITLE
Wrong capacity and same Unique ID on different Spansion chips

### ISSUE THREAD

**Issue by okwestern** [Marzogh/SPIMemory#140]
![GitHub issue state](https://img.shields.io/github/issues/detail/s/Marzogh/SPIFlash/140.svg) ![GitHub issue title](https://img.shields.io/github/issues/detail/title/Marzogh/SPIFlash/140.svg)
![GitHub issue author](https://img.shields.io/github/issues/detail/u/Marzogh/SPIFlash/140.svg) ![GitHub issue label](https://img.shields.io/github/issues/detail/label/Marzogh/SPIFlash/140.svg) ![GitHub issue comments](https://img.shields.io/github/issues/detail/comments/Marzogh/SPIFlash/140.svg)
![GitHub issue age](https://img.shields.io/github/issues/detail/age/Marzogh/SPIFlash/140.svg) ![GitHub issue last update](https://img.shields.io/github/issues/detail/last-update/Marzogh/SPIFlash/140.svg)
###### ---------------------------- **DO NOT DELETE OR EDIT** anything above this line ----------------------------

# Issue details

**I'm submitting a ...**
  - [x] bug report

Do the checklist before filing an issue:
- [x] Is this a bug that you cannot fix? Post the bug report as an issue here with a title that cleary says "Bug Report".

When opening an issue please include the following details:
-------------------------------------------------------------

- [x] Do you want to request a *feature* or report a *bug*? - bug
- [x] Which library version are you using? - 3.2.1
- [x] Which Arduino IDE version are you compiling the library on? - 1.8.5
- [x] Which OS are you compiling your code on? [Linux / Mac / Windows] - Mac
- [x] Which microcontroller platform are you using? - STM32F103RC
- [x] Which Flash memory module are you using? - S25FL032PIF (32Mb) and S25FL216K0PMFI011 (16Mb)
- [x] What is the current behavior? - Diagnostic shows 2M capacity (2097152) for both 32M and 16M chips. Diagnostic shows same unique ID (04294967040, 0xFFFFFFFFFFFFFF00) for both 32M and 16M chips. Specifying chip size with flash.begin(MB(32)); results in the same behaviour as not specifying chip size (flash.begin();) - output "No Chip size defined by user. Automated identification initiated."
- [x] What is the expected behavior? - Display correct capacity and unique id. Hardcoding chip size should be forced.

--------------------------
###### Bug reports only
- If this is a bug report -

- [x] Make sure you have run FlashDiagnostics.ino with ``` #define RUNDIAGNOSTICS ``` uncommented in SPIFlash.h. **List any error codes** that pop up in your Serial output when you run FlashDiagnostics.ino.here:

-

**Comment by Marzogh** [comment]
Thanks for catching this. I will look into it over the next week and get back to you. 😃 

My apologies for the long delay in replying. I was away for health reasons and am slowly transitioning back into normality.

**Comment by Marzogh** [comment]
Ah. I've just been catching up on the work I was doing before I fell ill and realised that the code in the development branch might solve your problem 🙂 

I suspect commit 3372c025f53336641fdb9fa854384be66937dfab fixes this issue. Could you please check using the latest code from the development branch and let me know if it does?
