### ISSUE TITLE
Adafruit's ItsyBitsy M4 support please.

### ISSUE THREAD

**Issue by SeuPay** [Marzogh/SPIMemory#142]
thanks,

**Comment by Marzogh** [comment]
Consider it done. I’m waiting for them to come back into stock so I can get my hands on one. 🙂

**Comment by Marzogh** [comment]
The microcontroller itself is supported in the latest release (I have tested it with the Metro M4). So, in theory, the library should work with the Itsy Bitsy M4 and any supported external flash chip.

**Comment by Marzogh** [comment]
v3.3.0 officially supports the ItsyBitsy M4. 🙂

**Comment by Wadreon** [comment]
What would the constructor look like for an M4?  I am trying to use with an feather M4 express. I gather if working with metro, should definitely work with feather. Though not certain on how to create constructor? Do not see a QSPI class. Thank You:)
