### ISSUE TITLE
Unable Read data

### ISSUE THREAD

**Issue by harissutanrafiq** [Marzogh/SPIMemory#153]
![GitHub issue state](https://img.shields.io/github/issues/detail/s/Marzogh/SPIFlash/153.svg) ![GitHub issue title](https://img.shields.io/github/issues/detail/title/Marzogh/SPIFlash/153.svg)
![GitHub issue author](https://img.shields.io/github/issues/detail/u/Marzogh/SPIFlash/153.svg) ![GitHub issue label](https://img.shields.io/github/issues/detail/label/Marzogh/SPIFlash/153.svg) ![GitHub issue comments](https://img.shields.io/github/issues/detail/comments/Marzogh/SPIFlash/153.svg)
![GitHub issue age](https://img.shields.io/github/issues/detail/age/Marzogh/SPIFlash/153.svg) ![GitHub issue last update](https://img.shields.io/github/issues/detail/last-update/Marzogh/SPIFlash/153.svg)

###### ---------------------------- **DO NOT DELETE OR EDIT** anything above this line ----------------------------

Hey there! Thanks for using the SPIFlash library for Arduino.
### Please note that starting 01.03.2018 any issue raised here MUST be submitted according to this template or it will be flagged with 'Not enough information'. No action will be taken till all the prerequisite information is provided. If no information is provided for over a month, the issue will be closed.

**Note: For support questions, please use the [Arduino Forums](http://forum.arduino.cc/index.php?topic=324009.0). This repository's issues are reserved for feature requests and bug reports.**

# Issue details

**I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

Do the checklist before filing an issue:

- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [ ] Is this an idea for a feature? Post the feature request as an issue here with a title that clearly says "Feature Request".
- [x] Is this a bug that you cannot fix? Post the bug report as an issue here with a title that cleary says "Bug Report".

When opening an issue please include the following details:
-------------------------------------------------------------

- [x] Do you want to request a *feature* or report a *bug*? bug
- [x] Which library version are you using? v3.2.1
- [x] Which Arduino IDE version are you compiling the library on? v1.8.3
- [x] Which OS are you compiling your code on? [Linux / Mac / Windows] Windows
- [x] Which microcontroller platform are you using? STM32F105xx
- [x] Which Flash memory module are you using? Winbond W25Q16JV
- [x] What is the current behavior? write then read is success, but failed read only from flash
- [x] What is the expected behavior? read data

--------------------------
###### Bug reports only
- If this is a bug report -

- [ ] Make sure you have run FlashDiagnostics.ino with ``` #define RUNDIAGNOSTICS ``` uncommented in SPIFlash.h. **List any error codes** that pop up in your Serial output when you run FlashDiagnostics.ino.here:
      Error codes
      ------------
        -
        -
        -
        -
        -
- [ ] If you have a problem with a particular function, call the flash.error() function (after you have made sure you have started up your Serial port with a ``` Serial.begin(BAUD) ``` ). Provide details of the function, the data given to/ expected from the function and the error code here: (**Please repeat this for every function you have an error with***)
        Function -
        Data -
        Error code -
- [x] Provide a **minimal code snippet** example that reproduces the bug. Please make sure you wrap any code in the proper code blocks like below
```
i have run FlashDiagnostics and its successfully no Error
I try write and then read back its success

//write_read.ino ///////////////

#include "SPIMemory.h"
SPIClass SPI_2(2);
SPIFlash flash(PB12, &SPI_2); 


uint32_t ADD1,ADD2;

char bf[201] ="CHAR ARRAY 1";
char bf2[201]="CHAR ARRAY 2";


void setup() {
  Serial2.begin(115200);

  delay(3000);
  
  flash.begin();

  ADD1 = flash.getAddress(200);
  ADD2 = flash.getAddress(500);

 
  if(flash.writeCharArray(ADD1, bf, strlen(bf) )){
    Serial2.println("Write string 1, success ");
  }
  
  if(flash.writeCharArray(ADD2, bf2, strlen(bf2))){
    Serial2.println("Write string 2, success ");
  }

  
}

void loop() {

  flash.readCharArray(ADD1,bf, strlen(bf));
  flash.readCharArray(ADD2,bf2, strlen(bf2) );

  Serial2.println(bf);
  Serial2.println(bf2);
  
  
  delay(5000);
}
[img]https://preview.ibb.co/mEzKGe/read_write.png[/img]

read.ino
---------------------------------------
#include "SPIMemory.h"
SPIClass SPI_2(2);
SPIFlash flash(PB12, &SPI_2); 


uint32_t ADD1,ADD2;

char bf[201] ="CHAR ARRAY 1";
char bf2[201]="CHAR ARRAY 2";


void setup() {
  Serial2.begin(115200);

  delay(3000);
  
  flash.begin();

  ADD1 = flash.getAddress(200);
  ADD2 = flash.getAddress(500);

 /*
  if(flash.writeCharArray(ADD1, bf, strlen(bf) )){
    Serial2.println("Write string 1, success ");
  }
  
  if(flash.writeCharArray(ADD2, bf2, strlen(bf2))){
    Serial2.println("Write string 2, success ");
  }
  */

  
}

void loop() {

  flash.readCharArray(ADD1,bf, strlen(bf));
  flash.readCharArray(ADD2,bf2, strlen(bf2) );

  Serial2.println(bf);
  Serial2.println(bf2);
  
  
  delay(5000);
}
[img]https://preview.ibb.co/jwsH2K/read.png[/img]

read.ino its failed, serial monitor is print unknown character please help me


```
- [x] Provide **screenshots** where appropriate
- [ ] Provide **wiring diagram** where appropriate

-----------------------------
###### Feature Requests only

- [ ] If this is a feature request, what is the motivation / use case for changing the behavior?

----------------------------

- [ ] Other information (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context etc.)

_Make sure to add **all the information needed to understand the bug/feature** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information._

**Comment by Marzogh** [comment]
I'm afraid the STM32F105xx is currently not officially supported as I do not have the dev board. I will keep this issue open in case someone who has an STM32F105xx dev board can help with a fix.

**Comment by Marzogh** [comment]
P.S. I've got my hands on a STM32F105xx dev board and v3.4.0 appears to work fine :)
