### ISSUE TITLE
Not really a issue but need help

### ISSUE THREAD

**Issue by josephchrzempiec** [Marzogh/SPIMemory#160]
Hello I'm still new to the whole arduino flash spi memory But i have a question will this library work on a winbond W25Q64JVSSIM it is a 64mbit spi flash memory? A friend of mine order a bunch of stuff and decided to send me some stuff because i told him I'm updating my esp8266 flash memory and maybe this can help me. But i would like to use it for my arduino projects. I just don't know what library would be good for it.

**Comment by Marzogh** [comment]
Hi mate, the library should work fine. If it does not work, let me know and I will fix it ASAP.

My apologies for the late reply. I've been away for a little over a year due to health reasons, but I'm back again. 🙂
