### ISSUE TITLE
Arduino nano

### ISSUE THREAD

**Issue by Zibri** [Marzogh/SPIMemory#162]
![GitHub issue state](https://img.shields.io/github/issues/detail/s/Marzogh/SPIFlash/162.svg) ![GitHub issue title](https://img.shields.io/github/issues/detail/title/Marzogh/SPIFlash/162.svg)
![GitHub issue author](https://img.shields.io/github/issues/detail/u/Marzogh/SPIFlash/162.svg) ![GitHub issue label](https://img.shields.io/github/issues/detail/label/Marzogh/SPIFlash/162.svg) ![GitHub issue comments](https://img.shields.io/github/issues/detail/comments/Marzogh/SPIFlash/162.svg)
![GitHub issue age](https://img.shields.io/github/issues/detail/age/Marzogh/SPIFlash/162.svg) ![GitHub issue last update](https://img.shields.io/github/issues/detail/last-update/Marzogh/SPIFlash/162.svg)
<hr>
Does this work also with arduino nano?

**Comment by Marzogh** [comment]
Yup. ITs got the same chip as the Uno and works fine
