### ISSUE TITLE
SST26VF06B Fails Write Test

### ISSUE THREAD

**Issue by jetty840** [Marzogh/SPIMemory#164]
![GitHub issue state](https://img.shields.io/github/issues/detail/s/Marzogh/SPIFlash/164.svg) ![GitHub issue title](https://img.shields.io/github/issues/detail/title/Marzogh/SPIFlash/164.svg)
![GitHub issue author](https://img.shields.io/github/issues/detail/u/Marzogh/SPIFlash/164.svg) ![GitHub issue label](https://img.shields.io/github/issues/detail/label/Marzogh/SPIFlash/164.svg) ![GitHub issue comments](https://img.shields.io/github/issues/detail/comments/Marzogh/SPIFlash/164.svg)
![GitHub issue age](https://img.shields.io/github/issues/detail/age/Marzogh/SPIFlash/164.svg) ![GitHub issue last update](https://img.shields.io/github/issues/detail/last-update/Marzogh/SPIFlash/164.svg)
<hr>
SST26VF06B fails all write tests on 3.2.1.  (Fresh flash, HOLD and WP held HIGH)

This was fixed previously by _disableGlobalBlockProtect, but it's no longer called from begin().

Calling _disableGlobalBlockProtect after "begin()"  makes it writable again.

**Comment by Marzogh** [comment]
Ugh! My bad! I'll get that sorted right away.

**Comment by Marzogh** [comment]
This is in fixed in the latest code in the dev branch - will go stable by tonight. The change will be rolled out in v3.3.0.
