### ISSUE TITLE
 memory code

### ISSUE THREAD

**Issue by schwiderke92** [Marzogh/SPIMemory#174]
can I use this flash memory to store the programming code?
Running as flash memory expansion?

**Comment by furtiman** [comment]
@schwiderke92 It seems to me that your question can be translated to "is it possible to implement a bootloader with this memory"?

**Comment by Marzogh** [comment]
I'm afraid the library does not let you use flash memory to store programming code -  it has never been one of the reasons for the library's existence. (Also, tbh, I'd have no idea how to get around to do that 🙂 ) If you modded the library to get that going, I'm happy to look at any pull requests to improve the library's functionality.
