### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by tarbear123** [Marzogh/SPIMemory#175]
how do you define the ChipSelect, do i need the wire library, do i put this in setup, i already have data_buffer, do i get rid of all the uint's and do i put my options in the curly brackets, do i put these in setup _startSPIBus(void); beginSPI(uint8_t opcode); begin(uint32_t flashChipSize = 0);

 readByteArray(uint32_t _addr, uint8_t *data_buffer, size_t bufferSize, bool fastRead = false);

**Comment by Marzogh** [comment]
Mate, have you looked at any of the examples included with the library?
