### ISSUE TITLE
Add support of HSPI on ESP32 

### ISSUE THREAD

**Issue by levkovigor** [Marzogh/SPIMemory#177]
In defines.h, SPIFlash.h and SPIFlash.cpp  should be added `|| defined(__XTENSA__)` to the line  `if defined (ARDUINO_ARCH_SAMD) || defined(ARCH_STM32)`. So it becomes possible to use HSPI on ESP32 `SPIFlash flash(15, new SPIClass(HSPI))`

**Comment by Marzogh** [comment]
Resolved as of commit b4676cb . Will be released as part of v3.4.0 code. For now, feel free to use the code from the 'stable' branch. 🙂
