### ISSUE TITLE
MX25L12845E

### ISSUE THREAD

**Issue by csaba911** [Marzogh/SPIMemory#37]
![GitHub issue state](https://img.shields.io/github/issues/detail/s/Marzogh/SPIFlash/37.svg) ![GitHub issue title](https://img.shields.io/github/issues/detail/title/Marzogh/SPIFlash/37.svg) ![GitHub issue author](https://img.shields.io/github/issues/detail/u/Marzogh/SPIFlash/37.svg) ![GitHub issue label](https://img.shields.io/github/issues/detail/label/Marzogh/SPIFlash/37.svg) ![GitHub issue comments](https://img.shields.io/github/issues/detail/comments/Marzogh/SPIFlash/37.svg) ![GitHub issue age](https://img.shields.io/github/issues/detail/age/Marzogh/SPIFlash/37.svg) ![GitHub issue last update](https://img.shields.io/github/issues/detail/last-update/Marzogh/SPIFlash/37.svg)
###### ---------------------------- **DO NOT DELETE OR EDIT** anything above this line ----------------------------
library works fine with 25Q64 Winbond chip but I'm unable make the necessary modification to read/write or even get chip id from MX25L12845E
Using standard SPI I'm able to read the chip id and random segment of memory address.

**Comment by Marzogh** [comment]
Hey mate, I'll look at the datasheet for the MX25L12845E and see what I can do. :) I'll post an update by the end of this week.

**Comment by Marzogh** [comment]
I'm afraid I haven't been able to source the chip, but, the current version of the library (v3.3.0) supports SFDP discovery. If you uncomment `#define USES_SFDP` in SPIMemory.h, it should let the library work with this chip.
