### ISSUE TITLE
Add ability to use Boards with different/multiple Serial ports easily

### ISSUE THREAD

**Issue by Marzogh** [Marzogh/SPIMemory#88]
![GitHub issue state](https://img.shields.io/github/issues/detail/s/Marzogh/SPIFlash/88.svg) ![GitHub issue title](https://img.shields.io/github/issues/detail/title/Marzogh/SPIFlash/88.svg) ![GitHub issue author](https://img.shields.io/github/issues/detail/u/Marzogh/SPIFlash/88.svg) ![GitHub issue label](https://img.shields.io/github/issues/detail/label/Marzogh/SPIFlash/88.svg) ![GitHub issue comments](https://img.shields.io/github/issues/detail/comments/Marzogh/SPIFlash/88.svg) ![GitHub issue age](https://img.shields.io/github/issues/detail/age/Marzogh/SPIFlash/88.svg) ![GitHub issue last update](https://img.shields.io/github/issues/detail/last-update/Marzogh/SPIFlash/88.svg)
###### ---------------------------- **DO NOT DELETE OR EDIT** anything above this line ----------------------------

**Comment by VitorBoss** [comment]
On Speeduino code have a similar code for serial
HardwareSerial &CANSerial = Serial2;

**Comment by Marzogh** [comment]
This was just an idea from back in the day that does not seem to receive much user interest and, I think the cost of bloat vs. any benefits isn't currently worth it. I'm packing this away for now.
